const db = {
hello: { translate: ['नमस्ते'], inenglish: ['namaste'] },
thankyou: { translate: ['धन्यवाद'], inenglish: ['dhanyavād'] },
book: { translate: ['किताब'], inenglish: ['kitaab'] },
bye: { translate: ['अलविदा'], inenglish: ['alavida'] },
welcome: { translate: ['स्वागत हे'], inenglish: ['svaagat he'] },
sorry: { translate: ['माफ़ करना'], inenglish: ['maaf karana'] },
please: { translate: ['कृपया'], inenglish: ['krpaya'] },
yes: { translate: ['हां'], inenglish: ['haan'] },
no: { translate: ['नहीं'], inenglish: ['nahin'] },
where: { translate: ['कहाँ पे'], inenglish: ['kahaan pe'] },
why: { translate: ['क्यों'], inenglish: ['kyon'] },
how: { translate: ['कैसे'], inenglish: ['kaise'] },  
when: { translate: ['कब'], inenglish: ['kab'] },
famous: { translate: ['प्रसिद्ध'], inenglish: ['prasiddh'] },
life: { translate: ['जिंदगी'], inenglish: ['jindagee'] },
dance: { translate: ['नृत्य'], inenglish: ['nruty'] },
sing: { translate: ['गाओ'], inenglish: ['gao'] }, 
act: { translate: ['कार्य'], inenglish: ['kary'] },
water: { translate: ['पानी'], inenglish: ['paani'] },
food: { translate: ['खाना'], inenglish: ['khaana'] },
dinner: { translate: ['रात का खाना'], inenglish: ['raat ka khaana'] },
breakfast: { translate: ['सुबह का नाश्ता'], inenglish: ['subah ka naashta'] },
lunch: { translate: ['दोपहर का भोजन'], inenglish: ['dopahar ka bhojan'] },
happy: { translate: ['प्रसन्न'], inenglish: ['prasann'] },
sad: { translate: ['दुखी'], inenglish: ['dukhee'] },
confuse: { translate: ['भ्रमित'], inenglish: ['bhrmit'] },
angry: { translate: ['गुस्सा'], inenglish: ['gussa'] },
guilt: { translate: ['अपराध'], inenglish: ['apradh'] },
woman: { translate: ['महिला'], inenglish: ['mahila'] },
man: { translate: ['पुरुष'], inenglish: ['purush'] },
people: { translate: ['लोग'], inenglish: ['log'] },
children: { translate: ['बच्चे'], inenglish: ['bachee'] },
day: { translate: ['दिन'], inenglish: ['din'] },
night: { translate: ['रात'], inenglish: ['raat'] },
noon: { translate: ['दोपहर'], inenglish: ['dopahar'] },
mother: { translate: ['मां'], inenglish: ['maa'] },
father: { translate: ['पिता'], inenglish: ['pita'] },
plants: { translate: ['पौधों'], inenglish: ['paudhon'] },
}
export default db;